; ===================================================================
;  Asterisk REST Interface (ARI)
;  El backend NestJS se conecta aquí vía WS para controlar llamadas.
; ===================================================================
[general]
enabled = yes
pretty = yes
allowed_origins = *
auth_realm = Asterisk REST Interface

[ariadmin]
type = user
read_only = no
password = change_me_ari
password_format = plain
