; ===================================================================
;  Asterisk HTTP server (necesario para ARI y para WSS WebRTC)
; ===================================================================
[general]
enabled = yes
bindaddr = 0.0.0.0
bindport = 8088
prefix =

; TLS para WebRTC en producción:
; tlsenable = yes
; tlsbindaddr = 0.0.0.0:8089
; tlscertfile = /etc/asterisk/keys/asterisk.pem
; tlsprivatekey = /etc/asterisk/keys/asterisk.key

session_limit = 200
session_inactivity = 30000
session_keep_alive = 15000
