[modules]
autoload = yes

; Excluir módulos que no usamos
noload = chan_sip.so          ; usamos PJSIP
noload = pbx_ael.so
noload = res_hep.so
noload = res_hep_pjsip.so
noload = res_hep_rtcp.so

; Asegurar que PJSIP, ARI, AMI, queues estén cargados
preload = res_config_curl.so
preload = res_curl.so

load = res_pjsip.so
load = res_pjsip_session.so
load = res_pjsip_outbound_registration.so
load = res_pjsip_endpoint_identifier_user.so
load = res_pjsip_endpoint_identifier_ip.so
load = res_pjsip_authenticator_digest.so
load = res_ari.so
load = res_ari_channels.so
load = res_ari_bridges.so
load = res_ari_recordings.so
load = res_ari_playbacks.so
load = res_ari_events.so
load = res_stasis.so
load = res_stasis_recording.so
load = res_stasis_playback.so
load = res_stasis_snoop.so
load = app_queue.so
load = app_voicemail.so
load = app_amd.so
load = app_dial.so
load = app_record.so
load = app_mixmonitor.so
load = chan_pjsip.so
